### ISSUE TITLE
Hyperparameter error 

### ISSUE THREAD

**Issue by jmaat** [openforcefield/openff-bespokefit#108]
When I specify hyperparameters with this line:
"""
        parameters=target_parameters,
        parameter_hyperparameters=[
            AngleHyperparameters(k=100, length=20),
            ImproperTorsionHyperparameters(k=5.0),
        ],
"""

 I am getting this error: 
"""
Traceback (most recent call last):
  File "/Users/jessica/Downloads/fit-example/2.create-fb-inputs.py", line 103, in <module>
    main()
  File "/Users/jessica/Downloads/fit-example/2.create-fb-inputs.py", line 80, in main
    AngleHyperparameters(k=100, length=20),
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for AngleHyperparameters
k
  extra fields not permitted (type=value_error.extra)
length
  extra fields not permitted (type=value_error.extra)
"""

@mattwthompson @JoshHorton

**Comment by jthorton** [comment]
Hi @jmaat you just need to enter the values as a dictionary under the arg priors like so 
```python
angle = AngleHyperparameters(priors={'k': 100})
```
this did also point out a bit of a bug that the angle hyperprameter has a length and not an angle I'll fix this today.

**Comment by jmaat** [comment]
Hi @jthorton thank you! I tried specifying the hyperparameters how you suggested and I am getting a new error saying I am missing a field and extra fields are not permitted. I'm wondering if you may know how to fix this - 
```
Traceback (most recent call last):
  File "/Users/jessica/Downloads/fit-example/2.create-fb-inputs.py", line 104, in <module>
    main()
  File "/Users/jessica/Downloads/fit-example/2.create-fb-inputs.py", line 56, in main
    optimization_schema = OptimizationSchema(
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 5 validation errors for OptimizationSchema
stages
  field required (type=value_error.missing)
optimizer
  extra fields not permitted (type=value_error.extra)
parameter_hyperparameters
  extra fields not permitted (type=value_error.extra)
parameters
  extra fields not permitted (type=value_error.extra)
targets
  extra fields not permitted (type=value_error.extra)
``` 


This is how I am specifying the hyper parameters - 
```
        parameter_hyperparameters=[
            AngleHyperparameters(priors={'k': 100, 'length'=110}),
            ImproperTorsionHyperparameters(priors={'k':5.0})
        ],
```

and I also tried defining angle and improper outside of the optimizationschema ( angle = AngleHyperparameters(priors={'k': 100, 'length'=110}), etc.) and got the same error..

**Comment by jthorton** [comment]
@jmaat it looks like you might be setting up the OptimizationSchema using an old set of arguments we recently reworked the schema to allow for multi-stage optimisation workflows when you might want to fit bonds and angles first then dihedrals or any other possible combination. I think you just need to move these arguments into an optimisation stage schema you can find the schemas [here](https://github.com/openforcefield/openff-bespokefit/blob/27b072bd09610dc8209429118d739e1f453edd61/openff/bespokefit/schema/fitting.py#L23).  If you can share how you are currently trying to setup the schema I should be able to convert it to the new format for you.

**Comment by jmaat** [comment]
thank you @jthorton . This is the current way I am doing the schema -
''' 
    angle = AngleHyperparameters(priors={'k': 100, 'length': 120}),
    improper = ImproperTorsionHyperparameters(priors={'k':5.0})
    optimization_schema = OptimizationSchema(
        id="optimize-improper-angle-parameters",
        initial_force_field=os.path.abspath(custom_force_field),
        # Define the optimizer / ForceBalance specific settings.
        optimizer=ForceBalanceSchema(
            max_iterations=50,
            step_convergence_threshold=0.01,
            objective_convergence_threshold=0.1,
            gradient_convergence_threshold=0.1,
            n_criteria=2,
            initial_trust_radius=-1.0,
            extras={"wq_port": "55125", "asynchronous": "True"},
        ),
        # Define the torsion profile targets to fit against.
        targets=[
            OptGeoTargetSchema(
                reference_data=optimization_training_set,
                weight=0.1,
                extras={"batch_size": 30, "remote": "1"},
            ),
        ],
        # Define the parameters to refit and the priors to place on them.
        parameters=target_parameters,
        parameter_hyperparameters=[
            angle,
            improper
        ],
    )
'''

**Comment by SimonBoothroyd** [comment]
@jmaat as Josh points out this issue is likely caused by a change to the API, the new syntax looks like:

```
angle = AngleHyperparameters(priors={'k': 100, 'length': 120})
improper = ImproperTorsionHyperparameters(priors={'k': 5.0})

optimization_schema = OptimizationSchema(
    id="optimize-improper-angle-parameters",
    initial_force_field=os.path.abspath(custom_force_field),
    # Define the optimizer / ForceBalance specific settings.
    stages=[
        OptimizationStageSchema(
            optimizer=ForceBalanceSchema(
                max_iterations=50,
                step_convergence_threshold=0.01,
                objective_convergence_threshold=0.1,
                gradient_convergence_threshold=0.1,
                n_criteria=2,
                initial_trust_radius=-1.0,
                extras={"wq_port": "55125", "asynchronous": "True"},
            ),
            # Define the torsion profile targets to fit against.
            targets=[
                OptGeoTargetSchema(
                    reference_data=optimization_training_set,
                    weight=0.1,
                    extras={"batch_size": 30, "remote": "1"},
                ),
            ],
            # Define the parameters to refit and the priors to place on them.
            parameters=target_parameters,
            parameter_hyperparameters=[
                angle,
                improper
            ],
        )
    ]
)
```

I also removed the comma from the end of the first line in your snippet as this will cause issues! Please feel free to re-open this if the issue persists.
