### ISSUE TITLE
No module named 'click'

### ISSUE THREAD

**Issue by bergazin** [openforcefield/openff-bespokefit#113]
When trying to run bespoke on the command line I get the following error:

```
Traceback (most recent call last):
  File "/Users/daniellebergaziin/anaconda/bin/openff-bespoke", line 33, in <module>
    sys.exit(load_entry_point('openff-bespokefit', 'console_scripts', 'openff-bespoke')())
  File "/Users/daniellebergaziin/anaconda/bin/openff-bespoke", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/daniellebergaziin/anaconda/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 166, in load
    module = import_module(match.group('module'))
  File "/Users/daniellebergaziin/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/daniellebergaziin/bespoke_setup/openff-bespokefit/openff/bespokefit/cli/__init__.py", line 1, in <module>
    from openff.bespokefit.cli.cli import cli
  File "/Users/daniellebergaziin/bespoke_setup/openff-bespokefit/openff/bespokefit/cli/cli.py", line 1, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

I'm able to run bespoke in a jupyter notebook, and import click in the terminal. Anyone know how to fix this?

**Comment by jthorton** [comment]
Strange can you post the output of conda list from the env you are running this in?

**Comment by SimonBoothroyd** [comment]
@bergazin you might need to install `click` and `click-option-group` depending on how you created the environment:

```
conda install --yes -c conda-forge click click-option-group
```

Until a full release is made the easiest way to create a conda environment when using `bespokefit` is to run:

```
conda  env create --name openff-bespokefit --file devtools/conda-envs/test-env.yaml
```

Please feel free to open this if the issue persists.
