### ISSUE TITLE
Export to other format

### ISSUE THREAD

**Issue by xiki-tempula** [openforcefield/openff-bespokefit#154]
Hi, I wonder if it is possible to export the FF into other format? Such as the gromacs topology.

I usually use parmed to convert the topology but in this case, it won't work.

```
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout
import parmed

    # Load PDB
    mol = parmed.load_file('lig.sdf') # This is the input
    mol[0].save('lig.pdb')
    pdb = PDBFile('lig.pdb')
    # Create system
    ff = ForceField('lig.offxml')
    system = ff.createSystem(pdb.topology,
                             nonbondedMethod=PME,
                             nonbondedCutoff=12.0 * angstroms,
                             switchDistance=10.0 * angstroms,
                             constraints=HBonds, flexibleConstraints=True)
    structure = parmed.openmm.load_topology(pdb.topology, system=system,
                                            xyz=pdb.positions)
    structure.save('lig.top', format='gromacs', overwrite=True)
```
Gives
```
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "/Users/zwu/miniconda3_x86/envs/biosimspace/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-dfaf84a31ef0>", line 1, in <cell line: 1>
    runfile('/Users/zwu/Documents/protein-ligand-benchmark/2020-02-07_tyk2/bespokefit/convert.py', wdir='/Users/zwu/Documents/protein-ligand-benchmark/2020-02-07_tyk2/bespokefit')
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/zwu/Documents/protein-ligand-benchmark/2020-02-07_tyk2/bespokefit/convert.py", line 18, in <module>
    system = ff.createSystem(pdb.topology,
  File "/Users/zwu/miniconda3_x86/envs/biosimspace/lib/python3.9/site-packages/openmm/app/forcefield.py", line 1212, in createSystem
    templateForResidue = self._matchAllResiduesToTemplates(data, topology, residueTemplates, ignoreExternalBonds)
  File "/Users/zwu/miniconda3_x86/envs/biosimspace/lib/python3.9/site-packages/openmm/app/forcefield.py", line 1427, in _matchAllResiduesToTemplates
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 1 (UNL).  This might mean your input topology is missing some atoms or bonds, or possibly that you are using the wrong force field.
```

This seems to be an openMM issue so I wonder if I can have some of your help. Thanks.

**Comment by jthorton** [comment]
Hi @xiki-tempula glad you managed to make a bespoke force field! To export the parameters for a different simulation engine it is recommended that you make an OpenMM system using the OpenFF-Toolkit and then use OpenFF-Interchange or  parmed as you have above. Here are some notebook examples using [interchange](https://github.com/openforcefield/openff-toolkit/blob/stable/examples/using_smirnoff_in_amber_or_gromacs/export_with_interchange.ipynb) or [parmed](https://github.com/openforcefield/openff-toolkit/blob/stable/examples/using_smirnoff_in_amber_or_gromacs/convert_with_parmed.ipynb), I hope this helps let m know if you have any issues.

**Comment by jthorton** [comment]
@xiki-tempula not quite you need to use the OpenFF-Toolkit to read offxml force field files rather than OpenMM directly, see the code attached which should work on your example. Let me know if there is anything else I can help with!

```python
from openff.toolkit.typing.engines.smirnoff import ForceField
from openff.toolkit.topology import Molecule
import parmed

# load the molecule and the force field using the toolkit
molecule = Molecule.from_file("Archive/lig.sdf")
ff = ForceField("Archive/lig.offxml")

# create an openmm system
openmm_system = ff.create_openmm_system(molecule.to_topology())

# Convert OpenMM System to a ParmEd structure.
parmed_structure = parmed.openmm.load_topology(
    molecule.to_topology().to_openmm(), openmm_system, molecule.conformers[0]
)
parmed_structure.save("system.top", overwrite=True)
parmed_structure.save("system.gro", overwrite=True)
```

**Comment by xiki-tempula** [comment]
Thanks.

**Comment by xiki-tempula** [comment]
Ok one need to add the line of `parmed_structure.residues[0].name = "Lig"`
