### ISSUE TITLE
List available QC specs

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openff-bespokefit#220]
**Description**

It would be useful to have an API or CLI point that lists the available QC methods. Second to that, it could be documented in a static file.

Currently you need a fair amount of familiarity with the package and the rest of our ecosystem to know what methods are available. Some docstrings (i.e. [here](https://docs.openforcefield.org/projects/bespokefit/en/stable/getting-started/bespoke-cli.html#cmdoption-openff-bespoke-executor-run-default-qc-spec)) and [other docs](https://docs.openforcefield.org/projects/bespokefit/en/stable/getting-started/quick-start.html) imply a short list of supported specs but I don't think there's any centralized way to query what is and is not supported by what is currently installed on a machine.

**Comment by Yoshanuikabundi** [comment]
There is [the docs installation page](https://docs.openforcefield.org/projects/bespokefit/en/stable/getting-started/installation.html#reference-data-generators), which suggests how to install compatible QC engines, but it doesn't say how to specify them, and I agree that a CLI/API point would be really nice.

**Comment by jthorton** [comment]
Since we run everything via qcengine you can check this using the CLI in that package `qcengine info` will list the available packages which can be used to generate data, we could just add this to the docs?

**Comment by mattwthompson** [comment]
~~Do I need an extra dependency here?~~

```console
$ conda list | grep qc && qcengine info
openff-qcsubmit           0.4.1              pyhd8ed1ab_0    conda-forge
qcelemental               0.25.1             pyhd8ed1ab_1    conda-forge
qcengine                  0.26.0             pyhd8ed1ab_0    conda-forge
qcportal                  0.15.8             pyhd8ed1ab_0    conda-forge
>>> Version information
QCEngine:    v0.26.0
QCElemental: v0.25.1

>>> Program information
Available programs:
Traceback (most recent call last):
  File "/Users/mattthompson/mambaforge/envs/bespokefit-test/bin/qcengine", line 10, in <module>
    sys.exit(main())
  File "/Users/mattthompson/mambaforge/envs/bespokefit-test/lib/python3.9/site-packages/qcengine/cli.py", line 169, in main
    info_cli(args)
  File "/Users/mattthompson/mambaforge/envs/bespokefit-test/lib/python3.9/site-packages/qcengine/cli.py", line 132, in info_cli
    info_programs()
  File "/Users/mattthompson/mambaforge/envs/bespokefit-test/lib/python3.9/site-packages/qcengine/cli.py", line 88, in info_programs
    version = program.get_version()
  File "/Users/mattthompson/mambaforge/envs/bespokefit-test/lib/python3.9/site-packages/qcengine/programs/gcp.py", line 70, in get_version
    raise UnknownError(f"Could not identify GCP version
```

Looks like I have the same issue reported [upstream](https://github.com/MolSSI/QCEngine/issues/293), including the `gcp` alias I never manually set. I _also_ had _another_ `gcp`, this one some special version of `cp` included in GNU coreutils. Anyway, that works nicely once the dust on my machine is blown off:

```console
$ qcengine info programs
>>> Program information
Available programs:
rdkit:       v2022.9.4             /Users/mattthompson/mambaforge/envs/bespokefit-test/lib/python3.9/site-packages/rdkit/__init__.py
xtb:         v20.2                 /Users/mattthompson/mambaforge/envs/bespokefit-test/lib/python3.9/site-packages/xtb/__init__.py

Other supported programs:
adcc cfour dftd3 dftd4 entos gamess gcp mctc-gcp molpro mopac mp2d mrchem nwchem openmm psi4 qchem qcore s-dftd3 terachem terachem_fe terachem_pbs torchani turbomole

If you think available programs are missing, query for details: `python -c "import qcengine as qcng; qcng.get_program('<program>')"`
